### ISSUE TITLE
Value too long for type character results in failure during import books 

### ISSUE THREAD

**Issue by loughnane** [th3r00t/pyShelf#63]
During initial setup I select import and then, after several books have been processed, I get the following error.

```
...
...
...
2020-10-16 18:31:46.409 | INFO     | backend.lib.storage:insert_book:80 - American Exceptionalism and American Innocence
2020-10-16 18:31:46,480 ERROR    Error in connection handler
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/websockets/server.py", line 191, in handler
    await self.ws_handler(self, path)
  File "./backend/lib/pyShelf.py", line 84, in socketio
    await self.runImport()
  File "./backend/lib/pyShelf.py", line 69, in runImport
    Catalogue(self.config).import_books()
  File "./backend/lib/library.py", line 281, in import_books
    db.insert_book(book)
  File "./backend/lib/storage.py", line 86, in insert_book
    raise e
  File "./backend/lib/storage.py", line 65, in insert_book
    self.cursor.execute(
psycopg2.errors.StringDataRightTruncation: value too long for type character varying(255)
2020-10-16 18:31:46,491 WARNING  Executing <Task finished name='Task-163' coro=<WebSocketServerProtocol.handler() done, defined at /usr/local/lib/python3.8/dist-packages/websockets/server.py:118> result=None created at /usr/local/lib/python3.8/dist-packages/websockets/server.py:116> took 10.273 seconds
```

**Comment by th3r00t** [comment]
Thanks for this report!

**Comment by simcop2387** [comment]
I've run into this and It looks like it's probably on the book.rights value.

the epub has this in the contents.opf

```
    <dc:rights>Text copyright © 2019 by Dragonsteel Entertainment, LLC; Cover art copyright © 2019 by Charlie Bowater; Starsight map by Bryan Mark Taylor copyright © 2019 by Dragonsteel Entertainment, LLC; Additional illustrations by Isaac Stewart and Ben McSweeney copyright © 2018 by Dragonsteel&amp;#x00A0;Entertainment, LLC</dc:rights>
```

Which contains a string longer than 255 characters.  And truncating this fixes the import.  My specific book is Starsight by Brandon Sanderson

**Comment by simcop2387** [comment]
The best way to fix it is to likely stop using varchar() and instead just use the text type.  

https://www.postgresql.org/docs/13/datatype-character.html has the details about how they differ

**Comment by th3r00t** [comment]
The type should be adjusted here. This will likely squash this issue. I've just gotta get to it. or get a pr ;)
https://github.com/th3r00t/pyShelf/blob/8adcb0e1723597578ea34d2e60a276ad57e29384/src/interface/models.py

**Comment by simcop2387** [comment]
I may  make a PR later then for it.  Another good link for anyone coming back to this later

https://wiki.postgresql.org/wiki/Don%27t_Do_This#Don.27t_use_varchar.28n.29_by_default

**Comment by th3r00t** [comment]
Should be fixed with the latest merge
https://github.com/th3r00t/pyShelf/pull/73
